### ISSUE TITLE
Feature requests: Pass multiple `Whereable` to `select` shortcuts for easy `OR` queries

### ISSUE THREAD

**Issue by andybarron** [jawj/zapatos#105]
Trying to do something like this:
```ts
const conditions = [] // dynamic
if (something) {
  conditions.push({email: "hello@example.com"})
}
if (somethingElse) {
  conditions.push({phone: "+12345678910"})
}
db.selectOne("person", conditions)
```
Unless I'm missing something, we can only do this with `SQLFragment`s right now, which is a bit of a bear :)

To clarify, this would merge all the different top-level conditions using `OR`, since you can already use `Whereable`s for `AND`.

**Comment by jawj** [comment]
Sorry for the slow reply. Interesting to see a bunch of people on board with this.

It seems like a reasonable idea and quite feasible, but how about using the [`or` helper from `conditions.ts`](https://github.com/jawj/zapatos/blob/81e87a677dbce78ecedd2c05dfda347830ecdbf8/src/db/conditions.ts#L61) instead?

That would make your example:

```typescript
db.selectOne("person", db.conditions.or(conditions));
```

Or I tend to make a shortcut to conditions, which then just makes it `dc.or(conditions)`.

I appreciate that the functions in `conditions.ts` aren’t currently well documented …

**Comment by jawj** [comment]
Just had another look at this, prompted by #124.

The original suggestion is a very easy change, but I'm not sure about it. First, it's not very explicit: you kind of have to guess what the library's going to do with a `Whereable[]`. Second, the type-checking isn't very good, unless you write your conditions as object literals within the query.

For example, this is a runtime error but compiles fine:

```typescript
const cond = [
  { name: 'Jane Austen' },
  { xyz: 12 },
];

await db.select('authors', cond).run(pool);
```

I'll have another look at the `or` helper, though ...

**Comment by jawj** [comment]
OK, with a couple of tweaks, the `or`, `and` and `not` conditions can all take `Whereable`s, which gives us stuff like this:

```typescript
import { conditions as dc } from 'zapatos/db';

const cond = [
  { name: 'Jane Austen' },
  { isLiving: true },
];

await db.select('authors', dc.or(...cond)).run(pool);
await db.select('authors', dc.and(...cond)).run(pool);
await db.select('authors', dc.not({ name: 'Jane Austen' })).run(pool);
```

The `and` option isn't useful in this context, but could be useful if you were using weaker conditions via other condition helpers (`lt`, `gt`, `not`, etc).

The typing story is actually worse here than in the simple array case, because there's currently no mechanism for automatically restricting the `Whereable`s to the right table. So it would certainly be a good idea to explicitly type `cond` as `s.authors.Whereable[]`.

But I think this is still useful. I'm wondering whether to make only this change, or to allow a `Whereable[]` for `OR` queries too as originally requested. Any views, anyone?

**Comment by jawj** [comment]
This is released in 6.1.

**Comment by remidewitte** [comment]
Many thanks !

**Comment by vmingam** [comment]
It's my turn to thank you @jawj for this new feature and @andybarron to have open this issue.
