### ISSUE TITLE
Prevent SQL injections in FROM clause

### ISSUE THREAD

**Issue by nguyentoanit** [jawj/zapatos#112]
Hi,

I have a query with table name is summited from users. 
It's similar your sample in the docs:

```sql
const 
  nameSubmittedByUser = 'books"; DROP TABLE "authors"; --',
  title = await db.sql<any>`
    SELECT * FROM ${nameSubmittedByUser} LIMIT 1`.run(pool);  // NEVER do this!
```

Could we prevent SQL injections using zapatos utils?
I didn't find out a solution for this.

Thanks.

Ref: https://jawj.github.io/zapatos/#sql-template-interpolation-types

**Comment by jawj** [comment]
Right. As you've seen in the docs, this is generally a dangerous move, because there's no built-in way in Postgres to safely parameterise table names and suchlike.

I'm afraid Zapatos doesn't have anything to help you here. If I needed to allow users to specify tables used in queries, I'd probably want either to check the table name against a whitelist of table names, or to ensure that it matched `/^[a-z0-9_]+$/i`.
