### ISSUE TITLE
SQLFragment in Whereable doesn't compile correctly

### ISSUE THREAD

**Issue by maxweisel** [jawj/zapatos#115]
I'm trying to construct a query that will compile like this:
```sql
SELECT * FROM users WHERE user_id = (SELECT user_id FROM platform_users WHERE platform_user_id = 'test');
```

This block of code compiles to the expression above:
```typescript
const platformUserQuery = db.sql<s.platform_users.SQL, s.platform_users.Selectable[]>`
  SELECT ${'user_id'}
  FROM ${'platform_users'}
  WHERE ${{
    platform_user_id: 'test',
  }}`

const selectUserQuery = db.sql<s.users.SQL, s.platform_users.Selectable[]>`SELECT * FROM ${'users'} WHERE user_id = (${platformUserQuery})`
```

However, I'd love to be able to drop the `user_id = ` part of the select query and pass the first SQLFragment in as a Whereable like so:

```typescript
const platformUserQuery = db.sql<s.platform_users.SQL, s.platform_users.Selectable[]>`
  SELECT ${'user_id'}
  FROM ${'platform_users'}
  WHERE ${{
    platform_user_id: 'test',
  }}`

const selectUserQuery = db.sql<s.users.SQL, s.platform_users.Selectable[]>`SELECT * FROM ${'users'} WHERE ${{
  user_id: platformUserQuery
}})`
```

But when I do that, the compiled query looks like this:
```
{
  text: 'SELECT * FROM "users" WHERE ((\n' +
    '  SELECT "user_id"\n' +
    '  FROM "platform_users"\n' +
    '  WHERE ("platform_user_id" = $1))))',
  values: [ 'test' ]
}
```

Whereable accepts an SQLFragment, so I assume this would work, but I'm not sure why it's missing the `user_id = ` part of the final expression.

Max

**Comment by jawj** [comment]
When you [use a `SQLFragment` within a `Whereable`](https://jawj.github.io/zapatos/#whereable), it's down to you to use the `self` symbol to indicate where the column name should go. This gives maximum flexibility for conditions that aren't simple equality tests.

I've changed the table names to match what I already have set up, but your example query should otherwise look like this:

```typescript
const authorQuery = db.sql<s.authors.SQL, s.authors.Selectable[]>`
  SELECT ${'id'} FROM ${'authors'} WHERE ${{ name: 'Douglas Adams' }}`;

const bookQuery = db.sql<s.books.SQL, s.books.Selectable[]>`
  SELECT * FROM ${'books'} WHERE ${{ authorId: db.sql`${db.self} = (${authorQuery})` }}`;

await bookQuery.run(pool);

// runs: SELECT * FROM "books" WHERE (("authorId" = (SELECT "id" FROM "authors" WHERE ("name" = $1))))
```

I'm not sure the `Whereable` does you any favours here, though. It would be simpler just to write:

```typescript
const altBookQuery = db.sql<s.books.SQL, s.books.Selectable[]>`
  SELECT * FROM ${'books'} WHERE ${'authorId'} = (${authorQuery})`;

await altBookQuery.run(pool);

// runs: SELECT * FROM "books" WHERE "authorId" = (SELECT "id" FROM "authors" WHERE ("name" = $1))
```

Alternatively, my own preference for this kind of query would be to use a [pass-through lateral join via the `select` helpers](https://jawj.github.io/zapatos/#lateral-pass-through), like so:

```typescript
const lateralBookQuery = db.selectOne('authors', { name: 'Douglas Adams' }, {
  lateral: db.select('books', { authorId: db.parent('id') })
});

await lateralBookQuery.run(pool);
```

**Comment by maxweisel** [comment]
Perfect! Thanks for the info!
