### ISSUE TITLE
Column names with spaces break type generation

### ISSUE THREAD

**Issue by codetheweb** [jawj/zapatos#122]
I'm developing a library on top of Zapatos and am using the sample dataset [pagila](https://github.com/devrimgunduz/pagila) in my tests. The dataset includes a view (`public.customer_list`) that has a column name with a space in it (`a.postal_code AS "zip code"`). This results in the following type being generated, which doesn't compile:
```ts
   /**
      * **customer_list.zip code**
      * - `text` in database
      * - Nullable, no default
      */
    zip code: string | null;
```

I realize the Postgres convention is to not use spaces, and I can work around this for now by fixing or dropping the view--so by no means an urgent bug. Just wanted to log this in case someone else runs into the same issue.

**Comment by jawj** [comment]
Fair point.

This commit should fix it: https://github.com/jawj/zapatos/commit/695fba861565d6c6668a8598bd29b93892a021ac

I'll include that in the next release.

You'll still have trouble if a table name has spaces, though, since we can't quote TS namespaces. And I haven't thought about enum names and the like either ...
