### ISSUE TITLE
Use same collection of columns for multiple queries

### ISSUE THREAD

**Issue by SmokeyMcGasso** [jawj/zapatos#135]
First of all, thank you for the amazing library.

In order to not repeat myself too often, I would like to do this:
```
const defaultColumns = ['id', 'name', 'created']

// Query 1
db.select('table', db.all, { columns: defaultColumns }

// Query 2
db.select('table', db.all, { columns: defaultColumns }

// Etc..
```
However, typescript throws the following error:
`TS2322: Type 'string[]' is not assignable to type 'ColumnsOption<"table">'. Type 'string' is not assignable to type 'keyof Selectable'.`

I tried to use `const defaultColumns = <const>['id', 'name', 'created']` and other variants, but none seem to work. Is it possible to use the same array of columns for multiple queries, without resorting to raw queries?

**Comment by SmokeyMcGasso** [comment]
Great! Thank you for the quick response. Just FYI: The first throws the same error, but the second one works like a charm :)

**Comment by tetchel** [comment]
interesting, it works for me (but I am on an older version of TS and this library).

**Comment by jawj** [comment]
`const defaultColumns = <const>['id', 'name', 'created']` really ought to work, and I've just added a `readonly` to the definition of `ColumnsOption` (and a few other places this then cascaded to) so that, when we next have a release, it will. :)

In the meantime, my preferred idiom would be `const defaultColumns: schema.table.Column[] = ['id', 'name', 'created']`.
