### ISSUE TITLE
Question: Idiomatic INSERT using SELECT

### ISSUE THREAD

**Issue by sohrab-** [jawj/zapatos#177]
I was wondering if there is a more idiomatic way of doing this with Zapatos:

```sql
INSERT INTO deposits (customer_id, amount)
SELECT id, $2
FROM customers
WHERE customers.external_id = $1
```

From the top of my head, I think these below will work but wondering if I missed a feature that makes this nicer.

* Use a transaction to fetch the customer ID and then use the `db.insert` with the results
* Rawdog the whole thing with `db.sql`

**Comment by jawj** [comment]
I think right now you can only do this in raw SQL with `db.sql`, but I'll see if we can make the types on `db.insert` more flexible to enable this ...

**Comment by jawj** [comment]
Hmm. After a bit more thinking I don't think this is easy to achieve, because the shortcuts are set up to return JSON (rather than a plain result that could be inserted), and also you'd have to be careful to return all columns in the correct order, because there's nowhere to specify the column names to be inserted.

So I think raw SQL it will have to be. :(
