### ISSUE TITLE
table names in generated queries should include schema prefix

### ISSUE THREAD

**Issue by purge** [jawj/zapatos#3]
for reasons unrelated to this package for some reason my search_path keeps getting reset inside transactions. Regardless, it should include the schema when generating the queries.

**Comment by jawj** [comment]
I agree that ideally they would. However, I've never had a use for this myself, and I'm also not sure if it can be done without significantly complicating things (both the library and how it's used). If you have bright ideas about how to achieve it, do let me know.

**Comment by mrjjwright** [comment]
As an alternative, set up the Postgres schema search path to your needs, it’s quite flexible

**Comment by purge** [comment]
There were complications using search_path in this instance (it was erroneously being reset by a function) and it's not possible to use in all circumstances. I'm waiting for some tests to land in this project before i attempt to add schema support.

**Comment by moltar** [comment]
I think this one is essential for multiple schema support.

**Comment by RipTheJacker** [comment]
> I agree that ideally they would. However, I've never had a use for this myself, and I'm also not sure if it can be done without significantly complicating things (both the library and how it's used). If you have bright ideas about how to achieve it, do let me know.

I think the only issue is that zapatos still quotes the schema as if it were a table, so you get incorrect queries like `select "some_schema.table" ...` instead of `select "some_schema"."table" ...`. I think a model to follow would be how postgraphile handles this to map graphql types to tables by setting the search path using a config setting. Really the same setting in the zapatos config should probably apply here and set them as pg session variables when a query is run.

Other than just for schemas, other applications of this would be if you are using row level security and need to set a jwt/claim/user_id or something like that to use a security policy during a query. 

I believe a simple way to handle this could be a setting in the runtime config that will become a SQL fragment added to queries in core.ts. 

If @purge hasn't already, I'm happy to create a PR.

**Comment by kalda341** [comment]
In case anyone is interested, I've worked around the issue using the code here: https://stackoverflow.com/a/59887536

**Comment by TheNickmaster21** [comment]
This should most certainly be an option if it is added. One of the organizations I work for has a multi-tenant setup with schemas per tenant and we rely on setting the search path ourselves to work across identical schemas.

**Comment by jawj** [comment]
> If @purge hasn't already, I'm happy to create a PR.

I'll be happy to look at such a PR.

**Comment by jawj** [comment]
Thanks to generous sponsorship from [Seam](https://www.getseam.com/), commits providing schema support have just landed on `master` and should be available as version 6.0 when I've updated the documentation.

To recap: formerly, Zapatos would interrogate multiple schemas if these were listed in `zapatosconfig.json`, but wouldn't include schema names in the generated types, so that multiple schemas would work only if there were no name collisions between tables in different schemas.

With these changes, schema names can be prefixed to tables and enums, so that multiple schemas can be used even if they have names in common. The quoting logic for interpolated strings in SQL queries has been correspondingly updated (a corollary: if you've got dots in any of your schema or table names — `SELECT * FROM "my.insane.table"`, anyone? — I'm afraid you're now officially beyond help, although I think that would have long since broken the syntax of your Zapatos-generated `schema.ts` anyway).

By default, the `public` schema is treated the same as it (and indeed all schemas) used to be, such that enum and table names are unprefixed. This behaviour is driven by a new configuration option in `zapatosconfig.json`, `"unprefixedSchema"`, which defaults to `"public"`. If it happens that you've renamed `public`, or changed your `search_path`, you must set `"unprefixedSchema"` to the first schema in `search_path` that exists in your database. Alternatively, it's always possible to set `"unprefixedSchema": null`, which entails prefixes for all names in all schemas.

Anyway, the upshot is that if you're using only the Postgres default `public` schema, you should find there are minor cosmetic differences in the generated schema, but no functional changes (and thus no work for you to do).

If you're already using multiple schemas, some things will break and need fixing (hence the need for a major version bump). Namely: you'll need to add schema prefixes for all but the first schema in your `search_path`. For example, `db.select('tableInOtherSchema', db.all)` will become `db.select('otherSchema.tableInOtherSchema', db.all)`.

Global cross-table types such as `Table`, `Selectable` or `AllTablesAndViews` still include all items from all schemas, with their names now prefixed as necessary. If you want only the items from the `public` schema (or whichever schema is the first in your `search_path`), those are now separately namespaced (`public.Table`, `public.Selectable`, `public.AllTablesAndViews`) irrespective of the value set for `"unprefixedSchema"`.

An example is worth a thousand words, so here's an example SQL schema:

```sql
CREATE SCHEMA "US";
CREATE TYPE "US"."parties" AS ENUM
( 'Democrat'
, 'Republican'
, 'Green'
, 'Other'
);
CREATE TABLE "US"."states"
( "stateId" text PRIMARY KEY
, "stateName" text NOT NULL
);
CREATE TABLE "US"."districts"
( "districtId" int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
, "stateId" text NOT NULL REFERENCES "US"."states"
, "ordinality" int NOT NULL
);
CREATE TABLE "US"."representatives"
( "representativeId" int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
, "representativeName" text NOT NULL
, "party" "US"."parties" NOT NULL
, "districtId" int REFERENCES "US"."districts" NOT NULL
);

CREATE SCHEMA "UK";
CREATE TYPE "UK"."parties" AS ENUM
( 'Labour'
, 'Conservative'
, 'Green'
, 'Other'
);
CREATE TYPE "UK"."nations" AS ENUM
( 'Scotland'
, 'Wales'
, 'Northern Ireland'
, 'England'
);
CREATE TABLE "UK"."constituencies"
( "constituencyId" int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
, "constituencyName" text NOT NULL
, "nation" "UK"."nations" NOT NULL
);
CREATE TABLE "UK"."mps"
( "mpId" int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
, "mpName" text NOT NULL
, "party" "UK"."parties" NOT NULL
, "constituencyId" int REFERENCES "UK"."constituencies"  -- NULL for House of Lords
);
```

And here's some interaction with it using the new features in Zapatos:

```typescript
const [brighton, handstp] = await db.insert("UK.constituencies", [
  { constituencyName: 'Brighton Pavilion', nation: 'England' },
  { constituencyName: 'Holborn and St Pancras', nation: 'England' },
]).run(pool);

await db.insert("UK.mps", [
  { mpName: 'Caroline Lucas', party: 'Green', constituencyId: brighton.constituencyId },
  { mpName: 'Keir Starmer', party: 'Labour', constituencyId: handstp.constituencyId },
]).run(pool);

const [ny, ga] = await db.insert("US.states", [
  { stateId: 'NY', stateName: 'New York' },
  { stateId: 'GA', stateName: 'Georgia' },
]).run(pool);

const ca = await db.upsert("US.states", { stateId: 'CA', stateName: 'Cauliflower' }, "stateId").run(pool);
await db.update("US.states", { stateName: 'California' }, { stateId: ca.stateId }).run(pool);

const [ny14, ga5] = await db.insert("US.districts", [
  { stateId: ny.stateId, ordinality: 14 },
  { stateId: ga.stateId, ordinality: 5 },
]).run(pool);

await db.insert("US.representatives", [
  { representativeName: 'Alexandria Ocasio-Cortez', districtId: ny14.districtId, party: 'Democrat' },
  { representativeName: 'Nikema Williams', districtId: ga5.districtId, party: 'Democrat' },
]).run(pool);

const reps = await db.select("US.representatives", db.all, {
  lateral: {
    district: db.selectExactlyOne("US.districts", { districtId: db.parent() }, {
      lateral: {
        state: db.selectExactlyOne("US.states", { stateId: db.parent() })
      }
    })
  }
}).run(pool);

console.dir(reps, { depth: null });

const mps = await db.sql
  <s.UK.mps.SQL | s.UK.constituencies.SQL, (s.UK.mps.Selectable & s.UK.constituencies.Selectable)[]>
  `SELECT * FROM ${"UK.mps"}
    JOIN ${"UK.constituencies"} USING (${"constituencyId"})
    WHERE ${"party"} = ${db.param('Green')}`.run(pool);

console.dir(mps.map(mp => [mp.mpName, mp.constituencyName]));
```

**Comment by moltar** [comment]
Amazing! Thanks, @jawj and @seamapi! ❤️

**Comment by jawj** [comment]
Now released.
