### ISSUE TITLE
Support snake case for custom generated types.

### ISSUE THREAD

**Issue by PizzaPartyInc** [jawj/zapatos#42]
Hey! :)

This is more of an improvement request rather than a bug. It's related to `Custom types and domains` section of zapatos documentation. 

Currently defining domains using snake case would produce a snake_case types and file names, which is not something to be desired in typescript, while snake case identifiers are kind of prevalent with Postgres:

```SQL
CREATE DOMAIN some_object_name AS "jsonb";
```

will produce a file `PgSome_object_name.ts` with contents: 

```ts
/*
** Please do edit this file as needed **
It's a placeholder for a custom type definition
*/

export type PgSome_object_name = db.JSONValue;  // replace with your custom type or interface as desired
```
(in example above `db.` is underlined because we do not import it, but I think this is fine because we anyway want to replace it with a concrete typescript type)

It would be great if underscores would be recognized by zapatos as a start of a new word, first character of which would be capitalized. (to produce filename like `PgSomeObjectName.ts` and type `PgSomeObjectName`)

Going even further (which is just me thinking of customizability and not something desperately needed :) ), there might be a configuration option for file name generation, e.g to specify generation options to be able to produce filenames like `pg-some-object-name.ts` or `pg.some.object.name.ts`. At the very least, all zapatos-generated files start with lower letter, so custom generated ones might seem a bit off :)

**Comment by jawj** [comment]
> (in example above db. is underlined because we do not import it, but I think this is fine because we anyway want to replace it with a concrete typescript type)

This is definitely a bug (introduced recently when we started doing imports with prefixes), and I'll release a fix shortly.

> It would be great if underscores would be recognized by zapatos as a start of a new word, first character of which would be capitalized. (to produce filename like PgSomeObjectName.ts and type PgSomeObjectName)

I was slightly in two minds about this, but I think I'm sold. 

Elsewhere (for table and column names) we don't monkey about with the Postgres names — and for good reason, since it would hugely complicate stuff. But I guess that we do already mess with the type names, by prefixing `Pg` and upcasing the first letter. So it's probably a good idea to give the rest of the type names the same treatment.

It would be good to avoid unnecessary breakage of existing installations, though. So perhaps we'll do it this new way only if we detect no existing custom type names with underscores in. This complicates the codebase slightly, but it's probably worth it.

**Comment by jawj** [comment]
Hmm, the referenced commit does what I suggested, but I'm not entirely happy with how much cruft this introduces for quite a small cosmetic benefit. I'm going to ponder this some more ...

**Comment by jawj** [comment]
I've had another go at this in af0b23fc5b494220a39bc1f2f4d95831b27ef92b. Now it's just an opt-in option. Look OK?

**Comment by PizzaPartyInc** [comment]
Tested it out, looks good! Waiting for a released version.

Thanks! :)

**Comment by jawj** [comment]
Great. Please note that I have since renamed the options to more directly reflect what happens: 

    customTypesTransform: 'PgMy_type' | 'my_type' | 'PgMyType' | ((s: string) => string);

**Comment by PizzaPartyInc** [comment]
Yep, was testing using new values, luckily typescript provides a handy dropdown for available options :)

**Comment by jawj** [comment]
This will be in the 3.0 release, which is taking a little while since it also contains some much more drastic changes (see #44).

**Comment by jawj** [comment]
Now released.
