### ISSUE TITLE
Array handling when inserting into json/jsonb.

### ISSUE THREAD

**Issue by josephglanville** [jawj/zapatos#51]
`node-postgres` automatically handles stringifying JSON objects when inserting into `json`/`jsonb` but doesn't handle Javascript arrays in the same way because it's not aware of the destination column type.

Zapatos is schema aware so could handle this case when the destination column is one of `json` or `jsonb`.

See https://github.com/brianc/node-postgres/issues/442 for details.

**Comment by jawj** [comment]
Thanks. I'm [well aware of the issue](https://jawj.github.io/zapatos/#casting-parameters-to-json)!

Zapatos is currently only schema aware in terms of types, but not at runtime. We could probably achieve runtime awareness using [reflect-metadata](https://www.typescriptlang.org/docs/handbook/decorators.html#metadata), but since this is currently experimental and a bit exotic, I think it's probably best to stick to what Zapatos currently offers — i.e. switching how arrays are treated by default (with the `castArrayParamsToJson` option) and case-by-case (using the optional second argument to `param`).

**Comment by josephglanville** [comment]
I see, thanks for the pointer - I missed this when perusing the documentation.

If doing this automatically at a later date isn't on the cards feel free to close this as I think this will do for the use cases I had in mind.

**Comment by jawj** [comment]
OK, I'll close then. If we ever start using reflection for other purposes I'll think about whether it's worth supporting this too.
