### ISSUE TITLE
Order/filter by joined table column

### ISSUE THREAD

**Issue by andrenarchy** [jawj/zapatos#62]
First of all thank you for this amazing library!

I have two tables: 
```sql
CREATE TABLE files (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  path TEXT NOT NULL UNIQUE
);

CREATE TABLE images (
  file_id INTEGER REFERENCES files(id) NOT NULL UNIQUE,
  width INTEGER NOT NULL,
  height INTEGER NOT NULL
);
```

Is it possible to query the `images` table with the `files` table joined and sort by `created_at`? I tried the following but it doesn't work.

```typescript
const images = await db.select('images', db.all, {
  lateral: { file: db.selectExactlyOne('files', { id: db.parent('file_id') }) },
  order: { by: 'file.created_at', direction: 'ASC' }
}).run(pool)
```

Similarly, is it possible to filter by a joined table column? The following doesn't work:
```typescript
const images = await db.select('images', { 'file.path': '/test.jpg'} , {
  lateral: { file: db.selectExactlyOne('files', { id: db.parent('file_id') }) }
}).run(pool)
```

**Comment by sfsr12** [comment]
I'm not sure the direct answer to this - but have you tried looking at the SQL generated?  

```ts
const query= db.select('images', db.all, {
  lateral: { file: db.selectExactlyOne('files', { id: db.parent('file_id') }) },
  order: { by: 'file.created_at', direction: 'ASC' }
}).compile()
```

If you have that and the end result SQL you are looking for - maybe the solution will present itself to you.

**Comment by andrenarchy** [comment]
I did look at the SQL generated (without the order parameter because the above leads to a Typescript error). However, I don't know how to access the `created_at` column of the `files` table in the `order` clause. Let me know if you have any hints!

**Comment by sfsr12** [comment]
So, I'm new to Zapatos - so I might be missing a simple solution - but until someone else can chime in with a better and more proper solution this seems to generate order the way you are looking for:

```ts   
order: { by: db.raw("RESULT #> '{created_at}'"), direction: "ASC" },
```

**Comment by jawj** [comment]
Thanks, this is a good question. Approximately as @sfsr12 says, you need to use the internal `jsonb` column, `result`:

```typescript
    const sortedImages = await db.select('images', db.all, {
      lateral: { file: db.selectExactlyOne('files', { id: db.parent('file_id') }) },
      order: { by: db.sql`result->'created_at'`, direction: 'ASC' }
    }).run(pool);

    const matchingImages = await db.select('images', db.sql`result->>'path' = ${db.param('/imgs/b.jpg')}`, {
      lateral: { file: db.selectExactlyOne('files', { id: db.parent('file_id') }) }
    }).run(pool)
```

I wonder if this is wholly satisfactory ... but for now it works.

**Comment by andrenarchy** [comment]
Awesome, thank you! I will try tomorrow.

Just out of curiosity: does this approach use the indexes of the joined table properly?

**Comment by jawj** [comment]
> Just out of curiosity: does this approach use the indexes of the joined table properly?

I'm afraid I suspect not.

**Comment by andrenarchy** [comment]
So for using indexes I'd have to run a manual join via db.sql`...`?

**Comment by jawj** [comment]
Yes, a [standard (non-lateral) join](https://jawj.github.io/zapatos/#manual-joins-using-postgres-json-features) would be necessary, I think.

**Comment by andrenarchy** [comment]
Great, thank you! That's how I ended up doing it. Do you think it'd be possible to run create such (non-lateral) joins with the `db.select()` shortcut function in the future? That'd make Zapatos even more awesome. :smiley:

**Comment by jawj** [comment]
Agreed it would be handy, but I haven't so far found a nice way to make it work. The really nice thing about the lateral joins is that the queries are simply ordinary `select` queries nested inside each other, which means you get both the types and the query generation almost for free once you've implemented the basic `select`.

**Comment by felixfbecker** [comment]
I've been thinking about this problem as well. I think if the lateral selects were not wrapping the row into a `result` JSONB object like `SELECT to_jsonb(*) AS result`, but rather just did `SELECT *`, indexes could be used at least for one-level deep as you could `ORDER BY lateral_author.last_name` instead of `ORDER BY lateral_author->'last_name'`.

Anything deeper like `ORDER BY lateral_author.university->'name'` would of course still require a JSONB operator that doesn't hit indexes but in my uses the one-level sorting covers the majority of use cases.

For filtering, there is also the possibility to move the `WHERE` condition _inside_ the lateral query, but then the lateral would have to be an `INNER JOIN LATERAL` to ensure outer rows are getting filtered out based on the inner condition. Currently they always use `LEFT JOIN LATERAL` so all the columns would just become `NULL` and it would mess with `LIMIT`/`OFFSET` on the outer query. And of course this approach doesn't help for `ORDER` on the outer query. You'd need to "flatten" the nested laterals into the outer query and rewrite `parentTable` to reference the "parent" lateral for that.

@jawj Is there a strong reason why `select()` et al always wrap the column into a JSONB `result` object? My guess is it is just done for consistent casting of data types. The `JSONSelectable` and `Selectable` interfaces are usually almost identical though. Maybe there is a TypeScript way to type it correctly, similar to how `undefined` changes to `null` on laterals. Even if some casting is necessary it would be a fine trade-off to support indexed sorting.
