### ISSUE TITLE
db.conditions.e ? How do you select where value is null or is equal to a single value?

### ISSUE THREAD

**Issue by TheNickmaster21** [jawj/zapatos#73]
Enjoying using this library but I hit another snag. I cannot figure out a simpler way to write the below query. I expected to find a Db.conditions.e but there was not one. The conditions.or requires a sql fragment and I was unsure how to pass it one that just mean field = value other than using is not distinct from... I apologize if this is a bad question but I searched the Github and documents to no avail.

``` 
Db.selectOne('payroll', {
    enum_payroll_status_id: Db.conditions.or(
        Db.conditions.isNull,
        Db.conditions.isNotDistinctFrom(DBEnumPayrollStatus.SUBMITTED)
    )
})
```

**Comment by jawj** [comment]
Oh, this is an excellent point — we were missing the most obvious comparison operator of all! I guess because it is not needed in the simple case, where there is only one condition. 

The next release will include `eq` for this purpose.

You could of course otherwise write the condition as a `SQLFragment` by hand, i.e.

```typescript
db.selectOne('payroll', {
    enum_payroll_status_id: db.sql`
      ${db.self} IS NULL OR ${db.self} = ${db.param(DBEnumPayrollStatus.SUBMITTED)}`
})
```

**Comment by TheNickmaster21** [comment]
Thank you very much! Also, thank you for the SQLFragment example; I have been having trouble figuring out exactly the db.param works with the db.sql!
