### ISSUE TITLE
select column as

### ISSUE THREAD

**Issue by puckey** [jawj/zapatos#80]
I found myself going back to raw sql for a select statement because I needed to select a column with an alias name.

```js
db.sql`
    select country_title as country from place
`.run(pool)
```

I had some ideas how this might work api wise. (And apologies if this is already possible somehow and I missed it in the docs.)

The stripped down approach might be to use column/alias array pairs:

```js
  db.select('channel', db.all, {
    columns: [['name', 'alias'], 'normal_column']
  })
```

But you could also use an object literal with key/value being column/alias..

```js
  db.select('channel', db.all, {
    columns: [{ name: 'alias' }, 'normal_column']
  })
```

which could also allow multiple aliases in the object:
```js
  db.select('channel', db.all, {
    columns: [{ name: 'alias',  name_two: 'alias_2' }, 'normal_column']
  })
```

and when only needing aliases you could pass an object:
```js
  db.select('channel', db.all, {
    columns: { name: 'alias',  name_two: 'alias_2' }
  })
```

**Comment by jawj** [comment]
I think if I do it, I might do it like this:

```
db.select('channel', db.all, {
  columns: { name: 'alias',  name_two: 'alias_2', unchanged: true, also_unchanged: true }
})
```

And it seems like it's probably a nice feature to have.

**Comment by jawj** [comment]
OK, so I did a bit of work on this. First, I implemented what I suggested above, which enables this sort of thing:

```typescript
const allBookTitles = await db.selectExactlyOne("books", db.all, {
  columns: <const>{ title: 'aliasedTitle', updatedAt: 'aliasedUpdatedAt }
}).run(pool);
```

You can see this on [the `columnalises` branch](https://github.com/jawj/zapatos/compare/columnaliases).

I was unhappy with this for two reasons:

1. The `<const>` in that example seems unavoidable (otherwise the aliases just get typed `string` and can't be passed through to the result type.
2. The setup looks rather similar to the `extras` but is confusingly in reverse (for `extras`, the keys appear on the result; here, the values appear as keys on the result).

That got me thinking that perhaps the right approach was to extend the `extras` option instead. It was in fact already possible to use the `extras` option to return a column value under a different name, but it was a bit of a performance and involved manual typing:

```typescript
const allBookTitles = await db.selectOne("books", db.all, {
  order: { by: 'title', direction: 'ASC' },
  columns: [],
  extras: {
    bookTitle: db.sql<s.books.SQL, string | null>`${"title"}`,
    bookId: db.sql<s.books.SQL, number>`${"id"}`,
  }
}).run(pool);
```

So what I've now done is just extend the `extras` option to also accept a column name instead of a `SQLFragment`, and pass through the appropriate type:

```typescript
const allBookTitles = await db.selectOne("books", db.all, {
  order: { by: 'title', direction: 'ASC' },
  columns: [],
  extras: {
    bookTitle: "title",
    bookId: "id",
  }
}).run(pool);
```

I'll mull this a little longer, but am likely to include (and document) this approach in the next release.

**Comment by jawj** [comment]
Thanks. This is the kind of feedback I love to hear. :)

**Comment by jawj** [comment]
OK, this is now deployed in the 3.6.0 release.
