### ISSUE TITLE
null type in materialized views

### ISSUE THREAD

**Issue by puckey** [jawj/zapatos#81]
I noticed that types of columns in materialized views always have `null` added to them. Would it be possible to make this configurable in `columnOptions`?

**Comment by jawj** [comment]
This sounds like a bug — I'll investigate ...

**Comment by jawj** [comment]
Ah, OK. Having investigated, the issue is just that materialized view columns are always reported as nullable by Postgres. See, for example, https://stackoverflow.com/questions/47242219/how-to-indicate-that-a-column-is-not-nullable-when-creating-a-materialized-view

I'm keen to avoid adding additional complexity to the library, so maybe the better solution here is to manually set `attnotnull` as outlined in that Stack Overflow post if you need this.

**Comment by puckey** [comment]
Thanks – I had no idea this could be done through Postgres!
