### ISSUE TITLE
Postgres version requirement?

### ISSUE THREAD

**Issue by k3n** [jawj/zapatos#89]
Greetings, interesting project here! I'm unfortunately on an older PG release (9.6) and was wondering if there were any known limitations or incompatibilities? Or should this just work?

Thanks in advance.

**Comment by jawj** [comment]
Afraid you'll likely have trouble with `FETCH FIRST` in pg < 10.5, which I moved to in order to support `WITH TIES`. See #84 on this.

I'm not aware of any other incompatibilities.

It seems like a shame for this to keep you out, so let me think about bringing back `LIMIT` where `WITH TIES` isn't used.

**Comment by jawj** [comment]
OK. I just released 4.0.1, which should be OK on 9.6. Let me know if you run into any other problems!

**Comment by k3n** [comment]
Amazing! Thank you.
