### ISSUE TITLE
Numeric and money Postgres types should be typed as strings

### ISSUE THREAD

**Issue by jgonera** [jawj/zapatos#95]
They are [returned as a `string` by node-postgres](https://github.com/brianc/node-postgres/issues/811#issuecomment-116644535) because `number` will lose precision for certain decimal values and integers above `Number.MAX_SAFE_INTEGER`.

**Comment by jawj** [comment]
Thanks. Had a quick check of this. To reflect runtime values, it seems like:

* In a `Selectable` (e.g. from simple manual query), `numeric` and `money` should both be typed `string`
* In a `JSONSelectable` (e.g. from `db.select`), `numeric` should be typed `number`, and `money` should be typed `string`

I guess that for `Wherables`, `Insertables` and `Updatables` we should probably allow both `number` and `string` for both of them, if possible.

**Comment by jgonera** [comment]
Thanks for a quick reply, @jawj. This does seem to make sense from the point of view of what `node-postgres` returns by default. However, it will make helper functions that return `JSONSelectable` (`db.select`, etc.) unsuitable for certain applications (financial, science) that require the `numeric` precision to be preserved. I'm leaving `money` out of the discussion because even PostgreSQL official wiki recommends it [shouldn't be used for anything, even monetary values](https://wiki.postgresql.org/wiki/Don%27t_Do_This#Don.27t_use_money).

PostgresSQL preserves the precision even when returning [`numeric` in JSON](https://dba.stackexchange.com/questions/172387/jsonb-and-numeric-precision-and-scale) because JSON spec doesn't really say anything about the precision of the `number` type, it's simply JavaScript's default implementation's limitation. To work around this limitation `node-postgres` allows us to [override how PostgreSQL types are parsed](https://github.com/brianc/node-pg-types) so even when using JSON functions (`jsonb_agg`, etc.) one could supply a custom JSON parser in JavaScript such as https://github.com/sidorares/json-bigint or https://github.com/josdejong/lossless-json ([the default is `JSON.parse`](https://github.com/brianc/node-pg-types/blob/8594bc6befca3523e265022f303f1376f679b5dc/lib/textParsers.js#L177-L178)).

The problem is that without such an override mechanism in Zapatos we will always get wrong types in TypeScript if we do the overrides in `node-postgres`. I wouldn't bring it up if the type overrides were only done to satisfy a personal preference / coding style but in this case the application may be simply operating on wrong/imprecise data if we use the default types. The only workaround for now is to only use `db.sql` and never use helper functions but I think a) helper functions are very convenient, b) banning them would cause confusion when onboarding new developers to the codebase. How do you think this could be addressed?

**Comment by jgonera** [comment]
On a side note, I have mixed feelings about `JSONSelectable` in general. I've read https://github.com/jawj/mostly-ormless (it's a great write-up!) and based some of my code on it. I do understand that using PostgreSQL JSON functions is a simple and elegant way of doing joins without writing any TypeScript to manually glue the results into nested structures. However, I quickly gave up on it in my project because of a different returned format for `timestamptz`. It was too inconvenient to remember when I have to parse a string and when I don't. I considered overriding `node-postgres` to always return ISO strings for `timestamptz`, but now it seems like the discrepancy between "jsonified" types and regular types may bite us (me) more often.

I'm not sure what the solution could be. My gut feeling is telling me that this may be a recurring problem for certain users and that perhaps using JSON functions in Postgres for gluing nested data is not ideal if Zapatos aims to be a versatile PostgreSQL library (it's totally fine if that's not the goal though, I understand that this may not be a problem in your projects). Any thoughts?

**Comment by jawj** [comment]
Sorry for the slow reply. I certainly do aim for Zapatos to be a versatile and serious Postgres library, so type discrepancies and information loss issues need fixing.

I wasn't aware of these alternative JSON libraries, but switching the `pg` module to use them seems to be a good solution. Then the question is simply how to allow Zapatos users to customise the types returned for the relevant Postgres types. I think something pretty flexible would be good, to accommodate alternative libraries and their various options (e.g. `alwaysParseAsBig` in json-bigint).

So I'll have a think. Suggestions welcome meanwhile.

**Comment by jawj** [comment]
@cclark25 Huh, looks like I dropped the ball on `money`. Seems like I have it typed `number` in all circumstances (JSON and not), but it should be string instead (though accept numbers on insert/update). Stand by for an update ...

**Comment by jawj** [comment]
OK, [this is fixed](https://github.com/jawj/zapatos/commit/1643b414db25cc557d228e98836321781072ce31), and will be released in a moment as 5.0.4.

The bigger custom types overhaul still needs doing, though ...

**Comment by x-EricH-x** [comment]
Is any work around for to get Postgresql numeric type as string in TS at the moment?

I am using it in a database that store ethereum (and other crypto) data and numeric with exact precision is very much needed (because uint256 is extensively used in eth)

**Comment by rhlsthrm** [comment]
Just ran into this issue in prod! Was using uint256 numbers and saw loss of precision in our database.

**Comment by jawj** [comment]
Hey all. I appreciate that it's a while since this issue was filed, but perhaps you could comment on a proposed solution?

It's on this branch: https://github.com/jawj/zapatos/tree/json-numbers.

I've added a schema-generation-time configuration option, `customJSONParsingForLargeNumbers`. 

* If `customJSONParsingForLargeNumbers` is `false`, then the schema is generated as before — with `bigint` and `numeric` both typed as `number` in `JSONSelectable`s — but a warning is emitted.
* If `customJSONParsingForLargeNumbers` is `true`, then `bigint` is typed `(number | db.Int8String)` and `numeric` is typed `(number | db.NumericString)` in `JSONSelectable`s, and no warning is emitted.

Then at runtime, if `customJSONParsingForLargeNumbers` is `true` then you must call `db.enableCustomJSONParsingForLargeNumbers(pg)` before issuing any queries.

* This sets `pg` to use my own custom JSON parsing library (https://github.com/jawj/json-custom-numbers), and ensures that any number that's too big or too precise to be properly represented as a number in JS is returned as a string.
* The logic that powers this is here: https://github.com/jawj/zapatos/blob/json-numbers/src/db/customJSON.ts

The reason that the fields come back as `(number | db.Int8String)` and `(number | db.NumericString)` — rather than just `db.Int8String` or `db.NumericString` — is that we cannot tell from the JSON what the original column type was. The value `1`, for example, can occur in `real`, `int`, `bigint` and `numeric` fields. So to avoid ever returning strings for `real`, `int`, and so on, we always return 'safe' numbers as numbers, irrespective of the column type.

**Comment by jawj** [comment]
Oh, hang on. Actually, I don't think this is a viable approach, since there are values that (for example) should **not** be quoted when the column is `double precision` but **should** be quoted when it's `bigint` (e.g. `9007199254740993`). Back to the drawing board ...

**Comment by jawj** [comment]
No, scratch that, I think it does work after all! The ones that should be quoted of course cannot actually be stored/represented by a `double precision` column, so I think we're OK.

**Comment by jawj** [comment]
This should be fixed in 6.3, just released: https://jawj.github.io/zapatos/#custom-json-parsing-for-bigint-and-numeric
